#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4MCM 3.2
#
#  CloudPak for MultiCloud Management
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4mcm.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre

# Run Prerequisites
    #- role: 01_initialization
      
  

# Post installation tasks
    - role: 41_infra-install

