---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for MultiCloud Management
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: STORAGECLASS -       üëì Load parameters
  include_vars: ../00_config_cp4mcm.yaml


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Determine Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: STORAGECLASS -       üåè Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


# --------------------------------------------------------------------------------------------------------------------------------------
# If Storage Classes are overridden
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ‚òëÔ∏è  Determine Storage Class File Override
  set_fact: STORAGE_CLASS_LARGE_BLOCK={{ STORAGECLASS_BLOCK_OVERRIDE }}
  when: STORAGECLASS_BLOCK_OVERRIDE!="not_configured"


- name: STORAGECLASS -       ‚òëÔ∏è  Determine Storage Class Block Override
  set_fact: STORAGE_CLASS_FILE={{ STORAGECLASS_FILE_OVERRIDE }}
  when: STORAGECLASS_FILE_OVERRIDE!="not_configured"


# --------------------------------------------------------------------------------------------------------------------------------------
# Otherwise determine Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ‚òëÔ∏è  Determine File Storage Class
  shell: |
      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
      if [[ $CLUSTER_NAME =~ "fyre.ibm.com" ]];
      then
          echo "rook-cephfs"
      else
        if [[ $CLUSTER_NAME =~ "appdomain.cloud" ]];
        then
            echo "ibmc-file-gold-gid"
        else
          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
          if [[ $SC_DEFAULT_STRING =~ "(default)" ]];
          then
            echo ${SC_DEFAULT_STRING//\(*} 
          else
            echo "No default StorageClass defined. Unable to determine what SC to use." 
            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi
        fi
      fi
  register: INSTALL_DETECTED_STORAGECLASS
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"



# --------------------------------------------------------------------------------------------------------------------------------------
# Otherwise determine Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ‚òëÔ∏è  Determine Block Storage Class
  shell: |
      CLUSTER_NAME={{ CLUSTER_NAME.stdout_lines[0] }}
      if [[ $CLUSTER_NAME =~ "fyre.ibm.com" ]];
      then
          echo "rook-ceph-block"
      else
        if [[ $CLUSTER_NAME =~ "appdomain.cloud" ]];
        then
            echo "ibmc-block-gold"
        else
          # Use Default Class (storageclass.kubernetes.io/is-default-class:true)
          SC_DEFAULT_STRING=$(oc get sc | grep "(default)")
          if [[ $SC_DEFAULT_STRING =~ "(default)" ]];
          then
            echo ${SC_DEFAULT_STRING//\(*} 
          else
            echo "No default StorageClass defined. Unable to determine what SC to use." 
            echo "Please define one using storageclass.kubernetes.io/is-default-class:true"
            echo "or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi
        fi
      fi
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS
  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured"



# --------------------------------------------------------------------------------------------------------------------------------------
# Set File Storage Class
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       üíæ Set STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }}
  set_fact: STORAGE_CLASS_FILE={{ INSTALL_DETECTED_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_FILE_OVERRIDE=="not_configured"

# --------------------------------------------------------------------------------------------------------------------------------------
# Set Large Block Storage Class to same value
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       üíæ Set STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
  set_fact: STORAGE_CLASS_LARGE_BLOCK={{ INSTALL_DETECTED_BLOCK_STORAGECLASS.stdout_lines[0] }} 
  when: STORAGECLASS_BLOCK_OVERRIDE=="not_configured" 



# --------------------------------------------------------------------------------------------------------------------------------------
# Check File Storage Class exists
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ‚òëÔ∏è  Check File Storage Class exists {{ STORAGE_CLASS_FILE }}
  shell: |
          SC_EXISTS=$(oc get sc {{ STORAGE_CLASS_FILE }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
          if [[ $SC_EXISTS -gt 0 ]];
          then
            echo "OK"
          else
            echo "Storage Class does not exist!"
            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi     
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS



# --------------------------------------------------------------------------------------------------------------------------------------
# Check Large Block Storage Class exists
# --------------------------------------------------------------------------------------------------------------------------------------
- name: STORAGECLASS -       ‚òëÔ∏è  Check Large Block Storage Class exists {{ STORAGE_CLASS_LARGE_BLOCK }}
  shell: |
          SC_EXISTS=$(oc get sc {{ STORAGE_CLASS_LARGE_BLOCK }} --ignore-not-found --no-headers| wc -l|tr -d ' ')
          if [[ $SC_EXISTS -gt 0 ]];
          then
            echo "OK"
          else
            echo "Storage Class does not exist!"
            echo "Please revioew your block storage class or set the STORAGECLASS_XXX_OVERRIDE in the configuration file."
            exit 1
          fi     
  register: INSTALL_DETECTED_BLOCK_STORAGECLASS



- name: STORAGECLASS -       üíø Storage Class 
  debug: 
    msg: 
    - "** Global Storage Classes for CP4MCM installation *************************************************************************"
    - " CP4MCM Storage Class File:          {{STORAGE_CLASS_FILE}}"
    - " CP4MCM Storage Class Large Block:   {{STORAGE_CLASS_LARGE_BLOCK}}"

